In [3]:
import pandas as pd
df = pd.read_csv('spam.csv', sep=",")

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 606-607: invalid continuation byte

In [4]:
df = pd.read_csv('spam.csv', sep=",", encoding = "ISO-8859-1")

In [5]:
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [6]:
for element in df['Unnamed: 2']: print(element)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 PO Box 5249
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 the person is definitely special for u..... But if the person is so special
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 HOWU DOIN? FOUNDURSELF A JOBYET SAUSAGE?LOVE JEN XXX\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 wanted to say hi. HI!!!\" Stop? Send STOP to 62468"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
this wont even start........ Datz confidence.."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 PO Box 5249
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
GN
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
.;-):-D"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
just been in bedbut mite go 2 thepub l8tr if uwana mt up?loads a luv Jenxxx.\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 bt not his girlfrnd... G o o d n i g h t . . .@"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 I'll come up"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 don't miss ur best life for anything... Gud nyt..."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 just as a shop has to give a guarantee on what they sell. B. G."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 But at d end my love compromised me for everything:-(\".. Gud mornin:-)"
nan
nan
nan
nan
nan
 the toughest is acting Happy with all unspoken pain inside..\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 smoke hella weed\""
\" not \"what i need to do.\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
JUST GOT PAYED2DAY & I HAVBEEN GIVEN Aå£50 PAY RISE 4MY WORK & HAVEBEEN MADE PRESCHOOLCO-ORDINATOR 2I AM FEELINGOOD LUV\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 justthought iåÕd sayhey! how u doin?nearly the endof me wk offdam nevamind!We will have 2Hook up sn if uwant m8? loveJen x.\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
JUST REALLYNEED 2DOCD.PLEASE DONTPLEASE DONTIGNORE MYCALLS
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
u hav2hear it!c u sn xxxx\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 I don't mind
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 Dont Come Near My Body..!! Bcoz My Hands May Not Come 2 Wipe Ur Tears Off That Time..!Gud ni8"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Well there's still a bit left if you guys want to tonight
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
this wont even start........ Datz confidence.."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 but dont try to prove\" ..... Gud mrng..."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 SHE SHUDVETOLD U. DID URGRAN KNOW?NEWAY
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 but watever u shared should be true\"...."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 like you are the KING\"...! OR \"Walk like you Dont care
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 HAD A COOL NYTHO
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 don't miss ur best life for anything... Gud nyt..."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 PO Box 1146 MK45 2WT (2/3)"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 \"It is d wonderful fruit that a tree gives when it is being hurt by a stone.. Good night......"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 we made you hold all the weed\""
nan
nan
nan
nan
 but dont try to prove it..\" .Gud noon...."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 but dont try to prove it..\" .Gud noon...."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 its a miracle to Love a person who can't Love anyone except U...\" Gud nyt..."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 Gud night...."
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
 bt not his girlfrnd... G o o d n i g h t . . .@"
 that's the tiny street where the parking lot is"
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [8]:
file = open("spam.csv", "r")
for line in file:
    print(line)

v1,v2,,,

ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,

ham,Ok lar... Joking wif u oni...,,,

spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,

ham,U dun say so early hor... U c already then say...,,,

ham,"Nah I don't think he goes to usf, he lives around here though",,,

spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, ĺŁ1.50 to rcv",,,

ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,

ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,

spam,WINNER!! As a valued network customer you have been selected to receivea ĺŁ900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,,,

spam,Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030,,,

ham,"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.",,,

spam,"SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info",,,

spam,"URGENT! You have won a 1 week FREE membership in our ĺŁ100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18",,,

ham,I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.,,,

ham,I HAVE A DATE ON SUNDAY WITH WILL!!,,,

spam,"XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL",,,

ham,Oh k...i'm watching here:),,,

ham,Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.,,,

ham,Fine if thatĺŐs the way u feel. ThatĺŐs the way its gota b,,,

spam,"England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/ĚĽ1.20 POBOXox36504W45WQ 16+",,,

ham,Is that seriously how you spell his name?,,,

ham,I‰Ű÷m going to try for 2 months ha ha only joking,,,

ham,So Ě_ pay first lar... Then when is da stock comin...,,,

ham,Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?,,,

ham,Ffffffffff. Alright no way I can meet up with you sooner?,,,

ham,Just forced myself to eat a slice. I'm really not hungry tho. This sucks. Mark is getting worried. He knows I'm sick when I turn down pizza. Lol,,,

ham,Lol your always so convincing.,,,

ham,Did you catch the bus ? Are you frying an egg ? Did you make a tea? Are you eating your mom's left over dinner ? Do you feel my Love ?,,,

ham,"I'm back &amp; we're packing the car now, I'll let you know if there's room",,,

ham,Ahhh. Work. I vaguely remember that! What does it feel like? Lol,,,

ham,"Wait that's still not all that clear, were you not sure about me being sarcastic or that that's why x doesn't want to live with us",,,

ham,Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won't go there! Not doing too badly cheers. You? ,,,

ham,K tell me anything about you.,,,

ham,For fear of fainting with the of all that housework you just did? Quick have a cuppa,,,

spam,Thanks for your subscription to Ringtone UK your mobile will be charged ĺŁ5/month Please confirm by replying YES or NO. If you reply NO you will not be charged,,,

ham,Yup... Ok i go home look at the timings then i msg Ě_ again... Xuhui going to learn on 2nd may too but her lesson is at 8am,,,

ham,"Oops, I'll let you know when my roommate's done",,,

ham,I see the letter B on my car,,,

ham,Anything lor... U decide...,,,

ham,Hello! How's you and how did saturday go? I was just texting to see if you'd decided to do anything tomo. Not that i'm trying to invite myself or anything!,,,

ham,Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola,,,

ham,"Did I forget to tell you ? I want you , I need you, I crave you ... But most of all ... I love you my sweet Arabian steed ... Mmmmmm ... Yummy",,,

spam,07732584351 - Rodger Burns - MSG = We tried to call you re your reply to our sms for a free nokia mobile + free camcorder. Please call now 08000930705 for delivery tomorrow,,,

ham,WHO ARE YOU SEEING?,,,

ham,Great! I hope you like your man well endowed. I am  &lt;#&gt;  inches...,,,

ham,No calls..messages..missed calls,,,

ham,Didn't you get hep b immunisation in nigeria.,,,

ham,"Fair enough, anything going on?",,,

ham,"Yeah hopefully, if tyler can't do it I could maybe ask around a bit",,,

ham,U don't know how stubborn I am. I didn't even want to go to the hospital. I kept telling Mark I'm not a weak sucker. Hospitals are for weak suckers.,,,

ham,What you thinked about me. First time you saw me in class.,,,

ham,"A gram usually runs like  &lt;#&gt; , a half eighth is smarter though and gets you almost a whole second gram for  &lt;#&gt;",,,

ham,K fyi x has a ride early tomorrow morning but he's crashing at our place tonight,,,

ham,"Wow. I never realized that you were so embarassed by your accomodations. I thought you liked it, since i was doing the best i could and you always seemed so happy about \the cave\"". I'm sorry I didn't and don't have more to give. I'm sorry i offered. I'm sorry your room was so embarassing.""",,,

spam,SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV,,,

ham,Do you know what Mallika Sherawat did yesterday? Find out now @  &lt;URL&gt;,,,

spam,"Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out! ",,,

ham,"Sorry, I'll call later in meeting.",,,

ham,Tell where you reached,,,

ham,Yes..gauti and sehwag out of odi series.,,,

ham,Your gonna have to pick up a $1 burger for yourself on your way home. I can't even move. Pain is killing me.,,,

ham,Ha ha ha good joke. Girls are situation seekers.,,,

ham,Its a part of checking IQ,,,

ham,"Sorry my roommates took forever, it ok if I come by now?",,,

ham,Ok lar i double check wif da hair dresser already he said wun cut v short. He said will cut until i look nice.,,,

spam,"As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a ĺŁ1500 Bonus Prize, call 09066364589",,,

ham,"Today is \song dedicated day..\"" Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me...""",,,

spam,"Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or ĺŁ1000. To claim txt DIS to 87121 18+6*ĺŁ1.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ",,,

spam,"Did you hear about the new \Divorce Barbie\""? It comes with all of Ken's stuff!""",,,

ham,I plane to give on this month end.,,,

ham,Wah lucky man... Then can save money... Hee...,,,

ham,Finished class where are you.,,,

ham,HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX,,,

ham,K..k:)where are you?how did you performed?,,,

ham,U can call me now...,,,

ham,I am waiting machan. Call me once you free.,,,

ham,Thats cool. i am a gentleman and will treat you with dignity and respect.,,,

ham,I like you peoples very much:) but am very shy pa.,,,

ham,Does not operate after  &lt;#&gt;  or what,,,

ham,Its not the same here. Still looking for a job. How much do Ta's earn there.,,,

ham,"Sorry, I'll call later",,,

ham,K. Did you call me just now ah? ,,,

ham,Ok i am on the way to home hi hi,,,

ham,You will be in the place of that man,,,

ham,Yup next stop.,,,

ham,"I call you later, don't have network. If urgnt, sms me.",,,

ham,For real when u getting on yo? I only need 2 more tickets and one more jacket and I'm done. I already used all my multis.,,,

ham,Yes I started to send requests to make it but pain came back so I'm back in bed. Double coins at the factory too. I gotta cash in all my nitros.,,,

ham,I'm really not up to it still tonight babe,,,

ham,"Ela kano.,il download, come wen ur free..",,,

ham,Yeah do! Don‰Ű÷t stand to close tho- you‰Ű÷ll catch something!,,,

ham,Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven't done any of y stuff42moro and that includes all my time sheets and that. Sorry. ,,,

ham,Smile in Pleasure Smile in Pain Smile when trouble pours like Rain Smile when sum1 Hurts U Smile becoz SOMEONE still Loves to see u Smiling!!,,,

spam,Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed ĺŁ1000 cash or ĺŁ5000 prize!,,,

ham,Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?,,,

spam,"Your free ringtone is waiting to be collected. Simply text the password \MIX\"" to 85069 to verify. Get Usher and Britney. FML", PO Box 5249," MK17 92H. 450Ppw 16""",

ham,Watching telugu movie..wat abt u?,,,

ham,i see. When we finish we have loads of loans to pay,,,

ham,"Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?\""

ham""",,,

ham,Please don't text me anymore. I have nothing else to say.,,,

ham,Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx,,,

ham,I'm still looking for a car to buy. And have not gone 4the driving test yet.,,,

ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,

ham,"wow. You're right! I didn't mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston.",,,

ham,Umma my life and vava umma love you lot dear,,,

ham,Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.,,,

ham,"Aight, I'll hit you up when I get some cash",,,

ham,How would my ip address test that considering my computer isn't a minecraft server,,,

ham,I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...,,,

ham,Dont worry. I guess he's busy.,,,

ham,What is the plural of the noun research?,,,

ham,Going for dinner.msg you after.,,,

ham,I'm ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.,,,

spam,GENT! We are trying to contact you. Last weekends draw shows that you won a ĺŁ1000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm,,,

ham,"Wa, ur openin sentence very formal... Anyway, i'm fine too, juz tt i'm eatin too much n puttin on weight...Haha... So anythin special happened?",,,

ham,"As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.",,,

spam,You are a winner U have been specially selected 2 receive ĺŁ1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ,,,

ham,Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed! ,,,

ham,Hmm...my uncle just informed me that he's paying the school directly. So pls buy food.,,,

spam,PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires,,,

spam,"URGENT! Your Mobile No. was awarded ĺŁ2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM",,,

ham,here is my new address -apples&pairs&all that malarky,,,

spam,Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app,,,

ham,I am going to sao mu today. Will be done only at 12 ,,,

ham,ĚĎ predict wat time Ě_'ll finish buying?,,,

ham,"Good stuff, will do.",,,

ham,"Just so that you know,yetunde hasn't sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn't have imposed anything on you in the first place so for that, i apologise.",,,

ham,Are you there in room.,,,

ham,HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx,,,

ham,K..k:)how much does it cost?,,,

ham,I'm home.,,,

ham,"Dear, will call Tmorrow.pls accomodate.",,,

ham,First answer my question.,,,

spam,Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. ĺŁ1.50 SP:Tyrone,,,

spam,Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK's largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p,,,

ham,I only haf msn. It's yijue@hotmail.com,,,

ham,He is there. You call and meet him,,,

ham,No no. I will check all rooms befor activities,,,

spam,You'll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again,,,

ham,Got c... I lazy to type... I forgot Ě_ in lect... I saw a pouch but like not v nice...,,,

ham,"K, text me when you're on the way",,,

ham,"Sir, Waiting for your mail.",,,

ham,"A swt thought: \Nver get tired of doing little things 4 lovable persons..\"" Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8""",,,

ham,I know you are. Can you pls open the back?,,,

ham,Yes see ya not on the dot,,,

ham,Whats the staff name who is taking class for us?,,,

spam,"FreeMsg Why haven't you replied to my text? I'm Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end",,,

ham,Ummma.will call after check in.our life will begin from qatar so pls pray very hard.,,,

ham,K..i deleted my contact that why?,,,

ham,Sindu got job in birla soft ..,,,

ham,The wine is flowing and i'm i have nevering..,,,

ham,Yup i thk cine is better cos no need 2 go down 2 plaza mah.,,,

ham,Ok... Ur typical reply...,,,

ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,

ham,"You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.",,,

ham,Aaooooright are you at work?,,,

ham,I'm leaving my house now...,,,

ham,"Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?",,,

spam,Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery,,,

spam,You are a winner U have been specially selected 2 receive ĺŁ1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810,,,

ham,Keep yourself safe for me because I need you and I miss you already and I envy everyone that see's you in real life,,,

ham,New car and house for my parents.:)i have only new job in hand:),,,

ham,I'm so in love with you. I'm excited each day i spend with you. You make me so happy.,,,

spam,-PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468,,,

spam,"BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu",,,

ham,I place all ur points on e cultures module already.,,,

spam,URGENT! We are trying to contact you. Last weekends draw shows that you have won a ĺŁ900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only,,,

ham,"Hi frnd, which is best way to avoid missunderstding wit our beloved one's?",,,

ham,Great escape. I fancy the bridge but needs her lager. See you tomo ,,,

ham,Yes :)it completely in out of form:)clark also utter waste.,,,

ham,"Sir, I need AXIS BANK account no and bank address.",,,

ham,"Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao... ",,,

ham,What time you coming down later? ,,,

ham,"Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m... ",,,

ham,"Well, i'm gonna finish my bath now. Have a good...fine night.",,,

ham,Let me know when you've got the money so carlos can make the call,,,

ham,U still going to the mall?,,,

ham,"Turns out my friends are staying for the whole show and won't be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth",,,

ham,Text her. If she doesnt reply let me know so i can have her log in,,,

ham,Hi! You just spoke to MANEESHA V. We'd like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.,,,

ham,You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend,,,

ham,Lol no. U can trust me.,,,

ham,ok. I am a gentleman and will treat you with dignity and respect.,,,

ham,"He will, you guys close?",,,

ham,Going on nothing great.bye,,,

ham,Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where's my boytoy now ? Does he miss me ?,,,

ham,"Haha awesome, be there in a minute",,,

spam,Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed ĺŁ1000 cash or ĺŁ5000 prize!,,,

ham,Have you got Xmas radio times. If not i will get it now,,,

ham,I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...,,,

spam,Are you unique enough? Find out from 30th August. www.areyouunique.co.uk,,,

ham,I'm sorry. I've joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|,,,

ham,Hi :)finally i completed the course:),,,

ham,It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.,,,

ham,How are you doing? Hope you've settled in for the new school year. Just wishin you a gr8 day,,,

ham,Gud mrng dear hav a nice day,,,

ham,Did u got that persons story,,,

ham,is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt? ,,,

ham,Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bloody babyjontet! Txt back if u can. :) xxx,,,

ham,"Found it, ENC  &lt;#&gt; , where you at?",,,

ham,I sent you  &lt;#&gt;  bucks,,,

ham,Hello darlin ive finished college now so txt me when u finish if u can love Kate xxx,,,

ham,Your account has been refilled successfully by INR  &lt;DECIMAL&gt; . Your KeralaCircle prepaid account balance is Rs  &lt;DECIMAL&gt; . Your Transaction ID is KR &lt;#&gt; .,,,

ham,Goodmorning sleeping ga.,,,

ham,U call me alter at 11 ok.,,,

ham,ĚĎ say until like dat i dun buy ericsson oso cannot oredi lar...,,,


In [9]:
file = open("spam.csv", "r")
for line in file:
    line = line.replace("am,","; ")
    line = line.replace(",,,","")
    print(line)

v1,v2

h; "Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."

h; Ok lar... Joking wif u oni...

sp; Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

h; U dun say so early hor... U c already then say...

h; "Nah I don't think he goes to usf, he lives around here though"

sp; "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, ĺŁ1.50 to rcv"

h; Even my brother is not like to speak with me. They treat me like aids patent.

h; As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune

sp; WINNER!! As a valued network customer you have been selected to receivea ĺŁ900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.

sp; Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030

h; "I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

sp; "SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info"

sp; "URGENT! You have won a 1 week FREE membership in our ĺŁ100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18"

h; I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.

h; I HAVE A DATE ON SUNDAY WITH WILL!!

sp; "XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL"

h; Oh k...i'm watching here:)

h; Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.

h; Fine if thatĺŐs the way u feel. ThatĺŐs the way its gota b

sp; "England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/ĚĽ1.20 POBOXox36504W45WQ 16+"

h; Is that seriously how you spell his name?

h; I‰Ű÷m going to try for 2 months ha ha only joking

h; So Ě_ pay first lar... Then when is da stock comin...

h; Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?

h; Ffffffffff. Alright no way I can meet up with you sooner?

h; Just forced myself to eat a slice. I'm really not hungry tho. This sucks. Mark is getting worried. He knows I'm sick when I turn down pizza. Lol

h; Lol your always so convincing.

h; Did you catch the bus ? Are you frying an egg ? Did you make a tea? Are you eating your mom's left over dinner ? Do you feel my Love ?

h; "I'm back &amp; we're packing the car now, I'll let you know if there's room"

h; Ahhh. Work. I vaguely remember that! What does it feel like? Lol

h; "Wait that's still not all that clear, were you not sure about me being sarcastic or that that's why x doesn't want to live with us"

h; Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won't go there! Not doing too badly cheers. You?

h; K tell me anything about you.

h; For fear of fainting with the of all that housework you just did? Quick have a cuppa

sp; Thanks for your subscription to Ringtone UK your mobile will be charged ĺŁ5/month Please confirm by replying YES or NO. If you reply NO you will not be charged

h; Yup... Ok i go home look at the timings then i msg Ě_ again... Xuhui going to learn on 2nd may too but her lesson is at 8; ,,

h; "Oops, I'll let you know when my roommate's done"

h; I see the letter B on my car

h; Anything lor... U decide...

h; Hello! How's you and how did saturday go? I was just texting to see if you'd decided to do anything tomo. Not that i'm trying to invite myself or anything!

h; Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola

h; "Did I forget to tell you ? I want you , I need you, I crave you ... But most of all ... I love you my sweet Arabian steed ... Mmmmmm ... Yummy"

sp; 07732584351 - Rodger Burns - MSG = We tried to call you re your reply to our sms for a free nokia mobile + free camcorder. Please call now 08000930705 for delivery tomorrow

h; WHO ARE YOU SEEING?

h; Great! I hope you like your man well endowed. I am  &lt;#&gt;  inches...

h; No calls..messages..missed calls

h; Didn't you get hep b immunisation in nigeria.

h; "Fair enough, anything going on?"

h; "Yeah hopefully, if tyler can't do it I could maybe ask around a bit"

h; U don't know how stubborn I am. I didn't even want to go to the hospital. I kept telling Mark I'm not a weak sucker. Hospitals are for weak suckers.

h; What you thinked about me. First time you saw me in class.

h; "A gram usually runs like  &lt;#&gt; , a half eighth is smarter though and gets you almost a whole second gram for  &lt;#&gt;"

h; K fyi x has a ride early tomorrow morning but he's crashing at our place tonight

h; "Wow. I never realized that you were so embarassed by your accomodations. I thought you liked it, since i was doing the best i could and you always seemed so happy about \the cave\"". I'm sorry I didn't and don't have more to give. I'm sorry i offered. I'm sorry your room was so embarassing."""

sp; SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV

h; Do you know what Mallika Sherawat did yesterday? Find out now @  &lt;URL&gt;

sp; "Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out! "

h; "Sorry, I'll call later in meeting."

h; Tell where you reached

h; Yes..gauti and sehwag out of odi series.

h; Your gonna have to pick up a $1 burger for yourself on your way home. I can't even move. Pain is killing me.

h; Ha ha ha good joke. Girls are situation seekers.

h; Its a part of checking IQ

h; "Sorry my roommates took forever, it ok if I come by now?"

h; Ok lar i double check wif da hair dresser already he said wun cut v short. He said will cut until i look nice.

sp; "As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a ĺŁ1500 Bonus Prize, call 09066364589"

h; "Today is \song dedicated day..\"" Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me..."""

sp; "Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or ĺŁ1000. To claim txt DIS to 87121 18+6*ĺŁ1.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ"

sp; "Did you hear about the new \Divorce Barbie\""? It comes with all of Ken's stuff!"""

h; I plane to give on this month end.

h; Wah lucky man... Then can save money... Hee...

h; Finished class where are you.

h; HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX

h; K..k:)where are you?how did you performed?

h; U can call me now...

h; I am waiting machan. Call me once you free.

h; Thats cool. i am a gentleman and will treat you with dignity and respect.

h; I like you peoples very much:) but am very shy pa.

h; Does not operate after  &lt;#&gt;  or what

h; Its not the same here. Still looking for a job. How much do Ta's earn there.

h; "Sorry, I'll call later"

h; K. Did you call me just now ah?

h; Ok i am on the way to home hi hi

h; You will be in the place of that man

h; Yup next stop.

h; "I call you later, don't have network. If urgnt, sms me."

h; For real when u getting on yo? I only need 2 more tickets and one more jacket and I'm done. I already used all my multis.

h; Yes I started to send requests to make it but pain came back so I'm back in bed. Double coins at the factory too. I gotta cash in all my nitros.

h; I'm really not up to it still tonight babe

h; "Ela kano.,il download, come wen ur free.."

h; Yeah do! Don‰Ű÷t stand to close tho- you‰Ű÷ll catch something!

h; Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven't done any of y stuff42moro and that includes all my time sheets and that. Sorry.

h; Smile in Pleasure Smile in Pain Smile when trouble pours like Rain Smile when sum1 Hurts U Smile becoz SOMEONE still Loves to see u Smiling!!

sp; Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed ĺŁ1000 cash or ĺŁ5000 prize!

h; Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?

sp; "Your free ringtone is waiting to be collected. Simply text the password \MIX\"" to 85069 to verify. Get Usher and Britney. FML", PO Box 5249," MK17 92H. 450Ppw 16""",

h; Watching telugu movie..wat abt u?

h; i see. When we finish we have loads of loans to pay

h; "Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?\""

ham"""

h; Please don't text me anymore. I have nothing else to say.

h; Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx

h; I'm still looking for a car to buy. And have not gone 4the driving test yet.

h; As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune

h; "wow. You're right! I didn't mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston."

h; Umma my life and vava umma love you lot dear

h; Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.

h; "Aight, I'll hit you up when I get some cash"

h; How would my ip address test that considering my computer isn't a minecraft server

h; I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...

h; Dont worry. I guess he's busy.

h; What is the plural of the noun research?

h; Going for dinner.msg you after.

h; I'm ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.

sp; GENT! We are trying to contact you. Last weekends draw shows that you won a ĺŁ1000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm

h; "Wa, ur openin sentence very formal... Anyway, i'm fine too, juz tt i'm eatin too much n puttin on weight...Haha... So anythin special happened?"

h; "As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there."

sp; You are a winner U have been specially selected 2 receive ĺŁ1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+)

h; Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed!

h; Hmm...my uncle just informed me that he's paying the school directly. So pls buy food.

sp; PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires

sp; "URGENT! Your Mobile No. was awarded ĺŁ2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM"

h; here is my new address -apples&pairs&all that malarky

sp; Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app

h; I am going to sao mu today. Will be done only at 12

h; ĚĎ predict wat time Ě_'ll finish buying?

h; "Good stuff, will do."

h; "Just so that you know,yetunde hasn't sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn't have imposed anything on you in the first place so for that, i apologise."

h; Are you there in room.

h; HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx

h; K..k:)how much does it cost?

h; I'm home.

h; "Dear, will call Tmorrow.pls accomodate."

h; First answer my question.

sp; Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. ĺŁ1.50 SP:Tyrone

sp; Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK's largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p

h; I only haf msn. It's yijue@hotmail.com

h; He is there. You call and meet him

h; No no. I will check all rooms befor activities

sp; You'll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again

h; Got c... I lazy to type... I forgot Ě_ in lect... I saw a pouch but like not v nice...

h; "K, text me when you're on the way"

h; "Sir, Waiting for your mail."

h; "A swt thought: \Nver get tired of doing little things 4 lovable persons..\"" Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8"""

h; I know you are. Can you pls open the back?

h; Yes see ya not on the dot

h; Whats the staff name who is taking class for us?

sp; "FreeMsg Why haven't you replied to my text? I'm Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end"

h; Ummma.will call after check in.our life will begin from qatar so pls pray very hard.

h; K..i deleted my contact that why?

h; Sindu got job in birla soft ..

h; The wine is flowing and i'm i have nevering..

h; Yup i thk cine is better cos no need 2 go down 2 plaza mah.

h; Ok... Ur typical reply...

h; As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune

h; "You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one."

h; Aaooooright are you at work?

h; I'm leaving my house now...

h; "Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?"

sp; Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery

sp; You are a winner U have been specially selected 2 receive ĺŁ1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810

h; Keep yourself safe for me because I need you and I miss you already and I envy everyone that see's you in real life

h; New car and house for my parents.:)i have only new job in hand:)

h; I'm so in love with you. I'm excited each day i spend with you. You make me so happy.

sp; -PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468

sp; "BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu"

h; I place all ur points on e cultures module already.

sp; URGENT! We are trying to contact you. Last weekends draw shows that you have won a ĺŁ900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only

h; "Hi frnd, which is best way to avoid missunderstding wit our beloved one's?"

h; Great escape. I fancy the bridge but needs her lager. See you tomo

h; Yes :)it completely in out of form:)clark also utter waste.

h; "Sir, I need AXIS BANK account no and bank address."

h; "Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao... "

h; What time you coming down later?

h; "Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m... "

h; "Well, i'm gonna finish my bath now. Have a good...fine night."

h; Let me know when you've got the money so carlos can make the call

h; U still going to the mall?

h; "Turns out my friends are staying for the whole show and won't be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth"

h; Text her. If she doesnt reply let me know so i can have her log in

h; Hi! You just spoke to MANEESHA V. We'd like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.

h; You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend

h; Lol no. U can trust me.

h; ok. I am a gentleman and will treat you with dignity and respect.

h; "He will, you guys close?"

h; Going on nothing great.bye

h; Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where's my boytoy now ? Does he miss me ?

h; "Haha awesome, be there in a minute"

sp; Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed ĺŁ1000 cash or ĺŁ5000 prize!

h; Have you got Xmas radio times. If not i will get it now

h; I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...

sp; Are you unique enough? Find out from 30th August. www.areyouunique.co.uk

h; I'm sorry. I've joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|

h; Hi :)finally i completed the course:)

h; It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.

h; How are you doing? Hope you've settled in for the new school year. Just wishin you a gr8 day

h; Gud mrng dear hav a nice day

h; Did u got that persons story

h; is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt?

h; Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bloody babyjontet! Txt back if u can. :) xxx

h; "Found it, ENC  &lt;#&gt; , where you at?"

h; I sent you  &lt;#&gt;  bucks

h; Hello darlin ive finished college now so txt me when u finish if u can love Kate xxx

h; Your account has been refilled successfully by INR  &lt;DECIMAL&gt; . Your KeralaCircle prepaid account balance is Rs  &lt;DECIMAL&gt; . Your Transaction ID is KR &lt;#&gt; .

h; Goodmorning sleeping ga.

h; U call me alter at 11 ok.

h; ĚĎ say until like dat i dun buy ericsson oso cannot oredi lar...

h; "As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there."

h; "Aight yo, dats straight dogg"

h; You please give us connection today itself before  &lt;DECIMAL&gt;  or refund the bill

h; Both :) i shoot big loads so get ready!

h; "What's up bruv, hope you had a great break. Do have a rewarding semester."

h; Home so we can always chat

h; K:)k:)good:)study well.

h; Yup... How Ě_ noe leh...

h; Sounds great! Are you home now?

h; Finally the match heading towards draw as your prediction.

h; Tired. I haven't slept well the past few nights.

h; Easy ah?sen got selected means its good..

h; I have to take exam with march 3

h; Yeah you should. I think you can use your gt atm now to register. Not sure but if there's anyway i can help let me know. But when you do be sure you are ready.

h; Ok no prob. Take ur time.


In [10]:
file_in = open("spam.csv", "r")
file_out = open("spam_marcin.csv", "w")
for line in file_in:
    line = line.replace("v1,v2","v1\tv2")
    line = line.replace("ham,","ham\t")
    line = line.replace("spam,","spam\t")
    line = line.replace(",,,","")
    file_out.write(line)

In [11]:
df = pd.read_table('spam_marcin.csv', sep="\t", encoding = "ISO-8859-1")

In [12]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5379   ham  Somebody set up a website where you can play h...
5380   ham   Its sunny in california. The weather's just cool
5381  spam         You have 1 new message. Call 0207-083-6089
5382   ham  I can make it up there, squeezed  &lt;#&gt;  b...
5383   ham  Good day to You too.Pray for me.Remove the tee...

[5384 rows x 2 columns]

In [13]:
df = pd.read_table('spam_marcin.csv', sep="\t", encoding = "ISO-8859-1", names = ["labels", "message"])

In [14]:
df

     labels                                            message
0        v1                                                 v2
1       ham  Go until jurong point, crazy.. Available only ...
2       ham                      Ok lar... Joking wif u oni...
3      spam  Free entry in 2 a wkly comp to win FA Cup fina...
4       ham  U dun say so early hor... U c already then say...
...     ...                                                ...
5380    ham  Somebody set up a website where you can play h...
5381    ham   Its sunny in california. The weather's just cool
5382   spam         You have 1 new message. Call 0207-083-6089
5383    ham  I can make it up there, squeezed  &lt;#&gt;  b...
5384    ham  Good day to You too.Pray for me.Remove the tee...

[5385 rows x 2 columns]